/**
 * Created by NickSp on 16.03.2017.
 */

var blogtexts = [];
blogtexts [0] = "Blog1";
blogtexts [1] = "May 25, 2017";
blogtexts [2] = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias consequuntur cumque eius expedita fuga incidunt ipsum laudantium numquam, odit praesentium, quia saepe, sequi sint sit ullam veniam voluptatibus. Aspernatur at dignissimos labore laudantium minima nam, nesciunt nihil optio. Architecto asperiores at consequatur delectus dolores facere facilis fugit inventore itaque magni, molestias mollitia natus non nostrum odit omnis, quibusdam sint unde. Adipisci, animi aspernatur debitis deserunt exercitationem, inventore magni, mollitia nesciunt nulla quo similique sit totam? Corporis ea error id. Adipisci autem expedita fugiat quam quod quos saepe. Modi sequi similique sit vitae voluptatem. Aliquid aperiam culpa cupiditate debitis delectus, eaque eligendi enim eum ex explicabo fugiat illo ipsam ipsum itaque iure maxime molestiae non obcaecati possimus provident quaerat quas, quis ratione sed soluta tempore totam voluptate. A accusantium architecto at aut consequatur corporis cumque dignissimos ea, ipsam laudantium maxime officiis perspiciatis similique sit tempora ullam velit veniam voluptate! Ab adipisci enim, est harum laborum nulla possimus quaerat qui rerum saepe sunt voluptatibus! Aperiam aut deleniti, dolorum et illo molestiae perferendis placeat quasi quisquam recusandae? Ab blanditiis cupiditate dolorum exercitationem expedita illo maxime minus modi obcaecati quasi, quisquam ratione saepe sunt suscipit veritatis! A culpa delectus facere ipsa necessitatibus nobis quas ratione, tempore tenetur vero. Consectetur error nesciunt porro! Eos, maiores, vel. Accusantium assumenda consequatur culpa cupiditate earum hic labore, reprehenderit sint sunt tempore. Ab, animi architecto at commodi consequuntur delectus ducimus eius eligendi eum eveniet laborum laudantium magnam minima necessitatibus numquam odit officiis sint suscipit velit vitae. Accusamus aperiam explicabo harum incidunt ipsam laborum minus nam obcaecati odio officia possimus quos tempore, voluptatum. Assumenda deleniti, dicta doloremque minus perferendis placeat quaerat saepe tenetur totam! Ab accusamus accusantium alias consequatur debitis doloremque doloribus dolorum facilis harum illo ipsa laudantium mollitia non nulla officia perspiciatis possimus ratione reprehenderit rerum tempore, tenetur vero?";
blogtexts [3] = "Blog2";
blogtexts [4] = "May 26, 2017";
blogtexts [5] = "Aspernatur at dignissimos labore laudantium minima nam, nesciunt nihil optio. Architecto asperiores at consequatur delectus dolores facere facilis fugit inventore itaque magni, molestias mollitia natus non nostrum odit omnis, quibusdam sint unde. Adipisci, animi aspernatur debitis deserunt exercitationem, inventore magni, mollitia nesciunt nulla quo similique sit totam? Corporis ea error id. Adipisci autem expedita fugiat quam quod quos saepe. Modi sequi similique sit vitae voluptatem. Aliquid aperiam culpa cupiditate debitis delectus, eaque eligendi enim eum ex explicabo fugiat illo ipsam ipsum itaque iure maxime molestiae non obcaecati possimus provident quaerat quas, quis ratione sed soluta tempore totam voluptate. A accusantium architecto at aut consequatur corporis cumque dignissimos ea, ipsam laudantium maxime officiis perspiciatis similique sit tempora ullam velit veniam voluptate! Ab adipisci enim, est harum laborum nulla possimus quaerat qui rerum saepe sunt voluptatibus! Aperiam aut deleniti, dolorum et illo molestiae perferendis placeat quasi quisquam recusandae? Ab blanditiis cupiditate dolorum exercitationem expedita illo maxime minus modi obcaecati quasi, quisquam ratione saepe sunt suscipit veritatis! A culpa delectus facere ipsa necessitatibus nobis quas ratione, tempore tenetur vero. Consectetur error nesciunt porro! Eos, maiores, vel. Accusantium assumenda consequatur culpa cupiditate earum hic labore, reprehenderit sint sunt tempore. Ab, animi architecto at commodi consequuntur delectus ducimus eius eligendi eum eveniet laborum laudantium magnam minima necessitatibus numquam odit officiis sint suscipit velit vitae. Accusamus aperiam explicabo harum incidunt ipsam laborum minus nam obcaecati odio officia possimus quos tempore, voluptatum. Assumenda deleniti, dicta doloremque minus perferendis placeat quaerat saepe tenetur totam! Ab accusamus accusantium alias consequatur debitis doloremque doloribus dolorum facilis harum illo ipsa laudantium mollitia non nulla officia perspiciatis possimus ratione reprehenderit rerum tempore, tenetur vero?";
blogtexts [6] = "Blog3";
blogtexts [7] = "May 27, 2017";
blogtexts [8] = "Architecto asperiores at consequatur delectus dolores facere facilis fugit inventore itaque magni, molestias mollitia natus non nostrum odit omnis, quibusdam sint unde. Adipisci, animi aspernatur debitis deserunt exercitationem, inventore magni, mollitia nesciunt nulla quo similique sit totam? Corporis ea error id. Adipisci autem expedita fugiat quam quod quos saepe. Modi sequi similique sit vitae voluptatem. Aliquid aperiam culpa cupiditate debitis delectus, eaque eligendi enim eum ex explicabo fugiat illo ipsam ipsum itaque iure maxime molestiae non obcaecati possimus provident quaerat quas, quis ratione sed soluta tempore totam voluptate. A accusantium architecto at aut consequatur corporis cumque dignissimos ea, ipsam laudantium maxime officiis perspiciatis similique sit tempora ullam velit veniam voluptate! Ab adipisci enim, est harum laborum nulla possimus quaerat qui rerum saepe sunt voluptatibus! Aperiam aut deleniti, dolorum et illo molestiae perferendis placeat quasi quisquam recusandae? Ab blanditiis cupiditate dolorum exercitationem expedita illo maxime minus modi obcaecati quasi, quisquam ratione saepe sunt suscipit veritatis! A culpa delectus facere ipsa necessitatibus nobis quas ratione, tempore tenetur vero. Consectetur error nesciunt porro! Eos, maiores, vel. Accusantium assumenda consequatur culpa cupiditate earum hic labore, reprehenderit sint sunt tempore. Ab, animi architecto at commodi consequuntur delectus ducimus eius eligendi eum eveniet laborum laudantium magnam minima necessitatibus numquam odit officiis sint suscipit velit vitae. Accusamus aperiam explicabo harum incidunt ipsam laborum minus nam obcaecati odio officia possimus quos tempore, voluptatum. Assumenda deleniti, dicta doloremque minus perferendis placeat quaerat saepe tenetur totam! Ab accusamus accusantium alias consequatur debitis doloremque doloribus dolorum facilis harum illo ipsa laudantium mollitia non nulla officia perspiciatis possimus ratione reprehenderit rerum tempore, tenetur vero?";
blogtexts [9] = "Blog4";
blogtexts [10] = "May 28, 2017";
blogtexts [11] = "Fuga incidunt ipsum laudantium numquam, odit praesentium, quia saepe, sequi sint sit ullam veniam voluptatibus. Aspernatur at dignissimos labore laudantium minima nam, nesciunt nihil optio. Architecto asperiores at consequatur delectus dolores facere facilis fugit inventore itaque magni, molestias mollitia natus non nostrum odit omnis, quibusdam sint unde. Adipisci, animi aspernatur debitis deserunt exercitationem, inventore magni, mollitia nesciunt nulla quo similique sit totam? Corporis ea error id. Adipisci autem expedita fugiat quam quod quos saepe. Modi sequi similique sit vitae voluptatem. Aliquid aperiam culpa cupiditate debitis delectus, eaque eligendi enim eum ex explicabo fugiat illo ipsam ipsum itaque iure maxime molestiae non obcaecati possimus provident quaerat quas, quis ratione sed soluta tempore totam voluptate. A accusantium architecto at aut consequatur corporis cumque dignissimos ea, ipsam laudantium maxime officiis perspiciatis similique sit tempora ullam velit veniam voluptate! Ab adipisci enim, est harum laborum nulla possimus quaerat qui rerum saepe sunt voluptatibus! Aperiam aut deleniti, dolorum et illo molestiae perferendis placeat quasi quisquam recusandae? Ab blanditiis cupiditate dolorum exercitationem expedita illo maxime minus modi obcaecati quasi, quisquam ratione saepe sunt suscipit veritatis! A culpa delectus facere ipsa necessitatibus nobis quas ratione, tempore tenetur vero. Consectetur error nesciunt porro! Eos, maiores, vel. Accusantium assumenda consequatur culpa cupiditate earum hic labore, reprehenderit sint sunt tempore. Ab, animi architecto at commodi consequuntur delectus ducimus eius eligendi eum eveniet laborum laudantium magnam minima necessitatibus numquam odit officiis sint suscipit velit vitae. Accusamus aperiam explicabo harum incidunt ipsam laborum minus nam obcaecati odio officia possimus quos tempore, voluptatum. Assumenda deleniti, dicta doloremque minus perferendis placeat quaerat saepe tenetur totam! Ab accusamus accusantium alias consequatur debitis doloremque doloribus dolorum facilis harum illo ipsa laudantium mollitia non nulla officia perspiciatis possimus ratione reprehenderit rerum tempore, tenetur vero?";
